/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_seraphyware_win7frametest_Win7Support */

#ifndef _Included_jp_seraphyware_win7frametest_Win7Support
#define _Included_jp_seraphyware_win7frametest_Win7Support
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_seraphyware_win7frametest_Win7Support
 * Method:    setCurrentProcessExplicitAppUserModelID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_seraphyware_win7frametest_Win7Support_setCurrentProcessExplicitAppUserModelID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_seraphyware_win7frametest_Win7Support
 * Method:    getCurrentProcessExplicitAppUserModelID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_seraphyware_win7frametest_Win7Support_getCurrentProcessExplicitAppUserModelID
  (JNIEnv *, jclass);

/*
 * Class:     jp_seraphyware_win7frametest_Win7Support
 * Method:    shutdownBlockReasonCreate
 * Signature: (Ljavax/swing/JFrame;)V
 */
JNIEXPORT void JNICALL Java_jp_seraphyware_win7frametest_Win7Support_shutdownBlockReasonCreate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jp_seraphyware_win7frametest_Win7Support
 * Method:    shutdownBlockReasonDestroy
 * Signature: (Ljavax/swing/JFrame;)V
 */
JNIEXPORT void JNICALL Java_jp_seraphyware_win7frametest_Win7Support_shutdownBlockReasonDestroy
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
